/* JavaParser.java */
/* Generated By:JavaCC: Do not edit this line. JavaParser.java */
package parser;
import parser.SymbolTable;import java.util.*;

public class JavaParser implements JavaParserConstants {
    // Use external parser.SymbolTable class
    private SymbolTable symbolTable = new SymbolTable();

    // Statistics for Phase 2
    private int classCount = 0;
    private int methodCount = 0;
    private int fieldCount = 0;
    private int statementCount = 0;
    private int expressionCount = 0;

    // Helper method to get clean token name
    private String getTokenName(Token token) {
        String name = tokenImage[token.kind];
            if (name.equals("\u005c"<\u005c"") || name.equals("\u005c">\u005c"") || name.equals("\u005c"<=\u005c"") || name.equals("\u005c">=\u005c"")) {
                return "Operator";  // Keep the operator as is (without any cleaning)
            }
        name = name.replace("\u005c"", "").replace("<","").replace(">","");

        // Map to token type names
    switch (name) {
            case "class":
            case "public":
            case "private":
            case"protected":
            case"final":
            case"const":
            case "static":
            case "void":
            case "int":
            case "double":
            case "float":
            case "long":
            case "short":
            case "byte":
            case "char":
            case "boolean":
            case "if":
            case "else":
            case "while":
            case "do":
            case "for":
            case "return":
            case "break":
            case "continue":
            case "true":
            case "false":
                return "Keyword";

            case "=":
            case "+":
            case "-":
            case "*":
            case "/":
            case "%":
            case "==":
            case "!=":
            case "<":
            case ">":
            case "<=":
            case ">=":
            case "&&":
            case "||":
            case "!":
                return "Operator";

            case "(":
            case ")":
            case "{":
            case "}":
            case "[":
            case "]":
            case ";":
            case ",":
            case ".":
                return "Delimiters";

            default:
                return name;
        }
    }

    private void recordToken(Token t) {
        symbolTable.addToken(t, getTokenName(t));
    }

    public void printSymbolTable() {
        symbolTable.printSymbolTable();
    }

    public void printVariables() {
        symbolTable.printVariables();
    }

    public void printStatistics() {
        System.out.println("\u005cn========================================");
        System.out.println("PARSING STATISTICS");
        System.out.println("========================================");
        System.out.println("Classes found:      " + classCount);
        System.out.println("Methods found:      " + methodCount);
        System.out.println("Fields found:       " + fieldCount);
        System.out.println("Statements found:   " + statementCount);
        System.out.println("Expressions found:  " + expressionCount);
    }

    public List<String> getUnusedVariables() {
        return symbolTable.getUnusedVariables();
        }

///=====================phase2:parsing====================///
  final public 
void Program() throws ParseException {
    ClassDeclaration();
    jj_consume_token(0);
System.out.println("-> Program Structure validate.");
  }

  final public void ClassDeclaration() throws ParseException {Token tCLASS,className,tRBRACE,tLBRACE;
        String modifiers = "";
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PUBLIC:
    case PRIVATE:
    case PROTECTED:
    case STATIC:{
      modifiers = Modifiers();
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    tCLASS = jj_consume_token(CLASS);
    className = jj_consume_token(IDENTIFIER);
recordToken(tCLASS);
recordToken(className);
classCount++;
 if (!modifiers.isEmpty()) {
            System.out.println("\u2192 Found class: " + modifiers + " " + className.image);
        } else {
            System.out.println("\u2192 Found class: " + className.image);
        }
    tLBRACE = jj_consume_token(LBRACE);
recordToken(tLBRACE);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUBLIC:
      case PRIVATE:
      case PROTECTED:
      case STATIC:
      case VOID:
      case INT:
      case LONG:
      case SHORT:
      case BYTE:
      case FLOAT:
      case DOUBLE:
      case STRING:
      case CHAR:
      case BOOLEAN:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      MemberDeclaration();
    }
    tRBRACE = jj_consume_token(RBRACE);
recordToken(tRBRACE);
  }

  final public void MemberDeclaration() throws ParseException {
    if (jj_2_1(2147483647)) {
      FieldDeclaration();
    } else if (jj_2_2(2147483647)) {
      MethodDeclaration();
    } else if (jj_2_3(2147483647)) {
      MethodDeclaration();
    } else if (jj_2_4(2147483647)) {
      FieldDeclaration();
    } else if (jj_2_5(2147483647)) {
      MethodDeclaration();
    } else if (jj_2_6(2147483647)) {
      MethodDeclaration();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void FieldDeclaration() throws ParseException {Token type,id,tSEMICOLON,tLBRACKET,tRBRACKET;
        String modifiers = "";
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PUBLIC:
    case PRIVATE:
    case PROTECTED:
    case STATIC:{
      modifiers = Modifiers();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    type = Type();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LBRACKET:{
      tLBRACKET = jj_consume_token(LBRACKET);
recordToken(tLBRACKET);
      tRBRACKET = jj_consume_token(RBRACKET);
recordToken(tRBRACKET);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    // Optional array brackets
             id = jj_consume_token(IDENTIFIER);
    tSEMICOLON = jj_consume_token(SEMICOLON);
fieldCount++;
recordToken(type);
recordToken(id);
recordToken(tSEMICOLON);
symbolTable.addVariable(id.image,type.image,id.beginLine);
 if (!modifiers.isEmpty()) {
            System.out.println("  \u2192 Field: " + modifiers + " " + type.image + " " + id.image);
        } else {
            System.out.println("  \u2192 Field: " + type.image + " " + id.image);
        }
  }

  final public void MethodDeclaration() throws ParseException {Token returnType,methodName,tRBRACE,tLBRACE,tLPAREN,tRPAREN;
    String modifiers = "";
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PUBLIC:
    case PRIVATE:
    case PROTECTED:
    case STATIC:{
      modifiers = Modifiers();
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:
    case LONG:
    case SHORT:
    case BYTE:
    case FLOAT:
    case DOUBLE:
    case STRING:
    case CHAR:
    case BOOLEAN:{
      returnType = Type();
      break;
      }
    case VOID:{
      returnType = jj_consume_token(VOID);
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
recordToken(returnType);
    methodName = jj_consume_token(IDENTIFIER);
recordToken(returnType);
recordToken(methodName);
        methodCount++;
 if (!modifiers.isEmpty()) {
            System.out.println("  \u2192 Method: " + modifiers + " " + returnType.image + " " + methodName.image + "()");
        } else {
            System.out.println("  \u2192 Method: " + returnType.image + " " + methodName.image + "()");
        }
    tLPAREN = jj_consume_token(LPAREN);
recordToken(tLPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:
    case LONG:
    case SHORT:
    case BYTE:
    case FLOAT:
    case DOUBLE:
    case STRING:
    case CHAR:
    case BOOLEAN:{
      ParameterList();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    tRPAREN = jj_consume_token(RPAREN);
recordToken(tRPAREN);
    tLBRACE = jj_consume_token(LBRACE);
recordToken(tLBRACE);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:
      case LONG:
      case SHORT:
      case BYTE:
      case FLOAT:
      case DOUBLE:
      case STRING:
      case CHAR:
      case BOOLEAN:
      case IF:
      case WHILE:
      case DO:
      case FOR:
      case RETURN:
      case BREAK:
      case CONTINUE:
      case SWITCH:
      case LBRACE:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_2;
      }
      Statement();
    }
    tRBRACE = jj_consume_token(RBRACE);
recordToken(tRBRACE);
  }

  final public void ParameterList() throws ParseException {
    Parameter();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_3;
      }
      jj_consume_token(COMMA);
      Parameter();
    }
  }

  final public void Parameter() throws ParseException {Token type,id,tLBRACKET,tRBRACKET;
    type = Type();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LBRACKET:{
      tLBRACKET = jj_consume_token(LBRACKET);
recordToken(tLBRACKET);
      tRBRACKET = jj_consume_token(RBRACKET);
recordToken(tRBRACKET);
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    // Optional array brackets
      id = jj_consume_token(IDENTIFIER);
recordToken(type);
recordToken(id);
symbolTable.addVariable(id.image,type.image,id.beginLine);
 System.out.println("  \u2192 Parameter: " + type.image + " " + id.image);
  }

  final public Token Type() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:{
      t = jj_consume_token(INT);
      break;
      }
    case LONG:{
      t = jj_consume_token(LONG);
      break;
      }
    case SHORT:{
      t = jj_consume_token(SHORT);
      break;
      }
    case BYTE:{
      t = jj_consume_token(BYTE);
      break;
      }
    case DOUBLE:{
      t = jj_consume_token(DOUBLE);
      break;
      }
    case FLOAT:{
      t = jj_consume_token(FLOAT);
      break;
      }
    case BOOLEAN:{
      t = jj_consume_token(BOOLEAN);
      break;
      }
    case CHAR:{
      t = jj_consume_token(CHAR);
      break;
      }
    case STRING:{
      t = jj_consume_token(STRING);
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return t;}
    throw new Error("Missing return statement in function");
  }

  final public String Modifiers() throws ParseException {Token mod;
    List<String> modList = new ArrayList<String>();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUBLIC:{
        mod = jj_consume_token(PUBLIC);
        break;
        }
      case PRIVATE:{
        mod = jj_consume_token(PRIVATE);
        break;
        }
      case PROTECTED:{
        mod = jj_consume_token(PROTECTED);
        break;
        }
      case STATIC:{
        mod = jj_consume_token(STATIC);
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
recordToken(mod);
            modList.add(mod.image);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUBLIC:
      case PRIVATE:
      case PROTECTED:
      case STATIC:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_4;
      }
    }
{if ("" != null) return String.join(" ", modList);}
    throw new Error("Missing return statement in function");
  }

  final public void Statement() throws ParseException {
statementCount++;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IF:{
      IfStatement();
      break;
      }
    case FOR:{
      ForStatement();
      break;
      }
    case WHILE:{
      WhileStatement();
      break;
      }
    case DO:{
      DoWhileStatement();
      break;
      }
    case RETURN:{
      ReturnStatement();
      break;
      }
    case LBRACE:{
      Block();
      break;
      }
    case BREAK:{
      BreakStatement();
      break;
      }
    case CONTINUE:{
      ContinueStatement();
      break;
      }
    case SWITCH:{
      SwitchStatement();
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      if (jj_2_7(2147483647)) {
        VariableDeclaration();
      } else if (jj_2_8(2147483647)) {
        AssignmentStatement();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFIER:{
          StatementExpression();
          break;
          }
        default:
          jj_la1[14] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
  }

  final public void StatementExpression() throws ParseException {
System.out.println("    \u2192 Expression statement");
    if (jj_2_9(2147483647)) {
      MemberAccess();
    } else if (jj_2_10(2147483647)) {
      MethodCall();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        jj_consume_token(IDENTIFIER);
recordToken(token);
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(SEMICOLON);
  }

  final public void VariableDeclaration() throws ParseException {Token type,id,tAssign,tSEMICOLON;
    type = Type();
    id = jj_consume_token(IDENTIFIER);
recordToken(type);
         recordToken(id);
         symbolTable.addVariable(id.image, type.image, id.beginLine);
         System.out.println("  \u2192 Variable declared: " + type.image + " " + id.image);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASSIGN:{
      tAssign = jj_consume_token(ASSIGN);
recordToken(tAssign);
      Expression();
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
    tSEMICOLON = jj_consume_token(SEMICOLON);
recordToken(tSEMICOLON);
  }

  final public void AssignmentStatement() throws ParseException {Token id,tAssign,tSEMICOLON;
    id = jj_consume_token(IDENTIFIER);
    tAssign = jj_consume_token(ASSIGN);
recordToken(id);
         recordToken(tAssign);
         System.out.println("  \u2192 Assignment to: " + id.image);
    Expression();
    tSEMICOLON = jj_consume_token(SEMICOLON);
recordToken(tSEMICOLON);
  }

  final public void IfStatement() throws ParseException {Token tIf,tElse,tLPAREN,tRPAREN;
    tIf = jj_consume_token(IF);
recordToken(tIf); System.out.println("  \u2192 If statement found");
    tLPAREN = jj_consume_token(LPAREN);
recordToken(tLPAREN);
    Expression();
    tRPAREN = jj_consume_token(RPAREN);
recordToken(tRPAREN);
    Statement();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      tElse = jj_consume_token(ELSE);
recordToken(tElse);
      Statement();
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      ;
    }
  }

  final public void WhileStatement() throws ParseException {Token t,tLPAREN,tRPAREN;
    t = jj_consume_token(WHILE);
recordToken(t);
 System.out.println("  \u2192 while loop found");
    tLPAREN = jj_consume_token(LPAREN);
recordToken(tLPAREN);
    Expression();
    tRPAREN = jj_consume_token(RPAREN);
recordToken(tRPAREN);
    Statement();
  }

  final public void DoWhileStatement() throws ParseException {Token tDo,tWhile,tLPAREN,tRPAREN;
    tDo = jj_consume_token(DO);
recordToken(tDo);
 System.out.println("  \u2192 Do while loop found");
    Statement();
    tWhile = jj_consume_token(WHILE);
recordToken(tWhile);
    tLPAREN = jj_consume_token(LPAREN);
recordToken(tLPAREN);
    Expression();
    tRPAREN = jj_consume_token(RPAREN);
recordToken(tRPAREN);
  }

  final public void ForStatement() throws ParseException {Token t,tLPAREN,tRPAREN,tSEMICOLON;
    t = jj_consume_token(FOR);
recordToken(t);
 System.out.println("  \u2192 for loop found");
    tLPAREN = jj_consume_token(LPAREN);
recordToken(tLPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:
    case LONG:
    case SHORT:
    case BYTE:
    case FLOAT:
    case DOUBLE:
    case STRING:
    case CHAR:
    case BOOLEAN:
    case IDENTIFIER:{
      ForInit();
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      ;
    }
    tSEMICOLON = jj_consume_token(SEMICOLON);
recordToken(tSEMICOLON);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TRUE:
    case FALSE:
    case MINUS:
    case NOT:
    case LPAREN:
    case INTEGER_LITERAL:
    case LONG_LITERAL:
    case FLOAT_LITERAL:
    case DOUBLE_LITERAL:
    case STRING_LITERAL:
    case CHAR_LITERAL:
    case IDENTIFIER:{
      Expression();
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      ;
    }
    tSEMICOLON = jj_consume_token(SEMICOLON);
recordToken(tSEMICOLON);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFIER:{
      ForUpdate();
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      ;
    }
    tRPAREN = jj_consume_token(RPAREN);
recordToken(tRPAREN);
    Statement();
  }

  final public void ForInit() throws ParseException {
    if (jj_2_11(2147483647)) {
      VariableDeclarationWithoutSemicolon();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        AssignmentWithoutSemicolon();
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void VariableDeclarationWithoutSemicolon() throws ParseException {Token type, id,tAssign;
    type = Type();
    id = jj_consume_token(IDENTIFIER);
recordToken(type);
        recordToken(id);
        symbolTable.addVariable(id.image, type.image, id.beginLine);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASSIGN:{
      tAssign = jj_consume_token(ASSIGN);
recordToken(tAssign);
      Expression();
      break;
      }
    default:
      jj_la1[22] = jj_gen;
      ;
    }
  }

  final public void AssignmentWithoutSemicolon() throws ParseException {Token id,tAssign;
    id = jj_consume_token(IDENTIFIER);
recordToken(id);
        symbolTable.markVariableUsed(id.image);
    tAssign = jj_consume_token(ASSIGN);
recordToken(tAssign);
    Expression();
  }

  final public void ForUpdate() throws ParseException {
    AssignmentWithoutSemicolon();
  }

  final public void ReturnStatement() throws ParseException {Token t,tSEMICOLON;
    t = jj_consume_token(RETURN);
recordToken(t);
 System.out.println("  \u2192 return statement found");
    Expression();
    tSEMICOLON = jj_consume_token(SEMICOLON);
recordToken(tSEMICOLON);
  }

  final public void Block() throws ParseException {Token tRBRACE,tLBRACE;
    tLBRACE = jj_consume_token(LBRACE);
recordToken(tLBRACE);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:
      case LONG:
      case SHORT:
      case BYTE:
      case FLOAT:
      case DOUBLE:
      case STRING:
      case CHAR:
      case BOOLEAN:
      case IF:
      case WHILE:
      case DO:
      case FOR:
      case RETURN:
      case BREAK:
      case CONTINUE:
      case SWITCH:
      case LBRACE:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        break label_5;
      }
      Statement();
    }
    tRBRACE = jj_consume_token(RBRACE);
recordToken(tRBRACE);
  }

  final public void BreakStatement() throws ParseException {Token t,tSEMICOLON;
    t = jj_consume_token(BREAK);
recordToken(t);
    tSEMICOLON = jj_consume_token(SEMICOLON);
recordToken(tSEMICOLON);
  }

  final public void ContinueStatement() throws ParseException {Token t,tSEMICOLON;
    t = jj_consume_token(CONTINUE);
recordToken(t);
    tSEMICOLON = jj_consume_token(SEMICOLON);
recordToken(tSEMICOLON);
  }

  final public void SwitchStatement() throws ParseException {Token t,tLPAREN,tRPAREN,tRBRACE,tLBRACE;
    t = jj_consume_token(SWITCH);
recordToken(t);
        System.out.println("    \u2192 Switch statement");
    tLPAREN = jj_consume_token(LPAREN);
recordToken(tLPAREN);
    Expression();
    tRPAREN = jj_consume_token(RPAREN);
recordToken(tRPAREN);
    tLBRACE = jj_consume_token(LBRACE);
recordToken(tLBRACE);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CASE:{
        ;
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        break label_6;
      }
      SwitchCase();
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DEFAULt:{
      DefaultCase();
      break;
      }
    default:
      jj_la1[25] = jj_gen;
      ;
    }
    tRBRACE = jj_consume_token(RBRACE);
recordToken(tRBRACE);
  }

  final public void SwitchCase() throws ParseException {Token t,tCOLON;
    t = jj_consume_token(CASE);
recordToken(t);
        System.out.println("      \u2192 Case branch");
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER_LITERAL:{
      jj_consume_token(INTEGER_LITERAL);
      break;
      }
    case CHAR_LITERAL:{
      jj_consume_token(CHAR_LITERAL);
      break;
      }
    case STRING_LITERAL:{
      jj_consume_token(STRING_LITERAL);
      break;
      }
    case IDENTIFIER:{
      jj_consume_token(IDENTIFIER);
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    tCOLON = jj_consume_token(COLON);
recordToken(tCOLON);
    label_7:
    while (true) {
      if (jj_2_12(2)) {
        ;
      } else {
        break label_7;
      }
      Statement();
    }
  }

  final public void DefaultCase() throws ParseException {Token t,tCOLON;
    t = jj_consume_token(DEFAULt);
recordToken(t);
        System.out.println("      \u2192 Default branch");
    tCOLON = jj_consume_token(COLON);
recordToken(tCOLON);
    label_8:
    while (true) {
      if (jj_2_13(2)) {
        ;
      } else {
        break label_8;
      }
      Statement();
    }
  }

  final public void Expression() throws ParseException {
expressionCount++;
    LogicalOrExpression();
  }

  final public void LogicalOrExpression() throws ParseException {Token t;
    LogicalAndExpression();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        break label_9;
      }
      t = jj_consume_token(OR);
recordToken(t);
      LogicalAndExpression();
    }
  }

  final public void LogicalAndExpression() throws ParseException {Token t;
    EqualityExpression();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        ;
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        break label_10;
      }
      t = jj_consume_token(AND);
recordToken(t);
      EqualityExpression();
    }
  }

  final public void EqualityExpression() throws ParseException {Token t;
    RelationalExpression();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQ:
      case NE:{
        ;
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        break label_11;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQ:{
        t = jj_consume_token(EQ);
recordToken(t);
        break;
        }
      case NE:{
        t = jj_consume_token(NE);
recordToken(t);
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      RelationalExpression();
    }
  }

  final public void RelationalExpression() throws ParseException {Token t;
    AdditiveExpression();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LT:
      case LE:
      case GT:
      case GE:{
        ;
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        break label_12;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LT:{
        t = jj_consume_token(LT);
recordToken(t);
        break;
        }
      case LE:{
        t = jj_consume_token(LE);
recordToken(t);
        break;
        }
      case GT:{
        t = jj_consume_token(GT);
recordToken(t);
        break;
        }
      case GE:{
        t = jj_consume_token(GE);
recordToken(t);
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      AdditiveExpression();
    }
  }

  final public void AdditiveExpression() throws ParseException {Token t;
    MultiplicativeExpression();
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:{
        ;
        break;
        }
      default:
        jj_la1[33] = jj_gen;
        break label_13;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        t = jj_consume_token(PLUS);
recordToken(t);
        break;
        }
      case MINUS:{
        t = jj_consume_token(MINUS);
recordToken(t);
        break;
        }
      default:
        jj_la1[34] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      MultiplicativeExpression();
    }
  }

  final public void MultiplicativeExpression() throws ParseException {Token t;
    UnaryExpression();
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DIVIDE:
      case MULTIPLY:{
        ;
        break;
        }
      default:
        jj_la1[35] = jj_gen;
        break label_14;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLY:{
        t = jj_consume_token(MULTIPLY);
recordToken(t);
        break;
        }
      case DIVIDE:{
        t = jj_consume_token(DIVIDE);
recordToken(t);
        break;
        }
      default:
        jj_la1[36] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      UnaryExpression();
    }
  }

  final public void UnaryExpression() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MINUS:
    case NOT:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NOT:{
        t = jj_consume_token(NOT);
recordToken(t);
        break;
        }
      case MINUS:{
        t = jj_consume_token(MINUS);
recordToken(t);
        break;
        }
      default:
        jj_la1[37] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      UnaryExpression();
      break;
      }
    case TRUE:
    case FALSE:
    case LPAREN:
    case INTEGER_LITERAL:
    case LONG_LITERAL:
    case FLOAT_LITERAL:
    case DOUBLE_LITERAL:
    case STRING_LITERAL:
    case CHAR_LITERAL:
    case IDENTIFIER:{
      PrimaryExpression();
      break;
      }
    default:
      jj_la1[38] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void PrimaryExpression() throws ParseException {Token t,tLPAREN,tRPAREN;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER_LITERAL:{
      t = jj_consume_token(INTEGER_LITERAL);
recordToken(t);
      break;
      }
    case LONG_LITERAL:{
      t = jj_consume_token(LONG_LITERAL);
recordToken(t);
      break;
      }
    case FLOAT_LITERAL:{
      t = jj_consume_token(FLOAT_LITERAL);
recordToken(t);
      break;
      }
    case DOUBLE_LITERAL:{
      t = jj_consume_token(DOUBLE_LITERAL);
recordToken(t);
      break;
      }
    case STRING_LITERAL:{
      t = jj_consume_token(STRING_LITERAL);
recordToken(t);
      break;
      }
    case CHAR_LITERAL:{
      t = jj_consume_token(CHAR_LITERAL);
recordToken(t);
      break;
      }
    case TRUE:{
      t = jj_consume_token(TRUE);
recordToken(t);
      break;
      }
    case FALSE:{
      t = jj_consume_token(FALSE);
recordToken(t);
      break;
      }
    default:
      jj_la1[39] = jj_gen;
      if (jj_2_14(2147483647)) {
        MemberAccess();
      } else if (jj_2_15(2147483647)) {
        MethodCall();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFIER:{
          t = jj_consume_token(IDENTIFIER);
recordToken(t);
          break;
          }
        case LPAREN:{
          tLPAREN = jj_consume_token(LPAREN);
recordToken(tLPAREN);
          Expression();
          tRPAREN = jj_consume_token(RPAREN);
recordToken(tRPAREN);
          break;
          }
        default:
          jj_la1[40] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
  }

  final public void MemberAccess() throws ParseException {Token id;
    id = jj_consume_token(IDENTIFIER);
recordToken(id);
    label_15:
    while (true) {
      jj_consume_token(DOT);
      id = jj_consume_token(IDENTIFIER);
recordToken(id);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:{
        jj_consume_token(LPAREN);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TRUE:
        case FALSE:
        case MINUS:
        case NOT:
        case LPAREN:
        case INTEGER_LITERAL:
        case LONG_LITERAL:
        case FLOAT_LITERAL:
        case DOUBLE_LITERAL:
        case STRING_LITERAL:
        case CHAR_LITERAL:
        case IDENTIFIER:{
          ArgumentList();
          break;
          }
        default:
          jj_la1[41] = jj_gen;
          ;
        }
        jj_consume_token(RPAREN);
        break;
        }
      default:
        jj_la1[42] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DOT:{
        ;
        break;
        }
      default:
        jj_la1[43] = jj_gen;
        break label_15;
      }
    }
  }

  final public void MethodCall() throws ParseException {Token id;
    id = jj_consume_token(IDENTIFIER);
recordToken(id);
        symbolTable.markVariableUsed(id.image);
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TRUE:
    case FALSE:
    case MINUS:
    case NOT:
    case LPAREN:
    case INTEGER_LITERAL:
    case LONG_LITERAL:
    case FLOAT_LITERAL:
    case DOUBLE_LITERAL:
    case STRING_LITERAL:
    case CHAR_LITERAL:
    case IDENTIFIER:{
      ArgumentList();
      break;
      }
    default:
      jj_la1[44] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
  }

  final public void MethodCallStatement() throws ParseException {
System.out.println("    \u2192 Method call statement");
    if (jj_2_16(2147483647)) {
      MemberAccess();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        MethodCall();
        break;
        }
      default:
        jj_la1[45] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(SEMICOLON);
  }

  final public void ArgumentList() throws ParseException {
    Expression();
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[46] = jj_gen;
        break label_16;
      }
      jj_consume_token(COMMA);
      Expression();
    }
  }

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_2_16(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  private boolean jj_3_13()
 {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_50()
 {
    if (jj_3R_55()) return true;
    return false;
  }

  private boolean jj_3R_35()
 {
    if (jj_3R_47()) return true;
    return false;
  }

  private boolean jj_3R_34()
 {
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3R_33()
 {
    if (jj_3R_45()) return true;
    return false;
  }

  private boolean jj_3R_32()
 {
    if (jj_3R_44()) return true;
    return false;
  }

  private boolean jj_3R_31()
 {
    if (jj_3R_43()) return true;
    return false;
  }

  private boolean jj_3R_30()
 {
    if (jj_3R_42()) return true;
    return false;
  }

  private boolean jj_3R_29()
 {
    if (jj_3R_41()) return true;
    return false;
  }

  private boolean jj_3_12()
 {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_28()
 {
    if (jj_3R_40()) return true;
    return false;
  }

  private boolean jj_3R_27()
 {
    if (jj_3R_39()) return true;
    return false;
  }

  private boolean jj_3R_26()
 {
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3R_24()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) {
    jj_scanpos = xsp;
    if (jj_3R_32()) {
    jj_scanpos = xsp;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_25()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(9)) {
    jj_scanpos = xsp;
    if (jj_scan_token(10)) {
    jj_scanpos = xsp;
    if (jj_scan_token(11)) {
    jj_scanpos = xsp;
    if (jj_scan_token(15)) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_17()
 {
    Token xsp;
    if (jj_3R_25()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_25()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_18()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(17)) {
    jj_scanpos = xsp;
    if (jj_scan_token(18)) {
    jj_scanpos = xsp;
    if (jj_scan_token(19)) {
    jj_scanpos = xsp;
    if (jj_scan_token(20)) {
    jj_scanpos = xsp;
    if (jj_scan_token(22)) {
    jj_scanpos = xsp;
    if (jj_scan_token(21)) {
    jj_scanpos = xsp;
    if (jj_scan_token(25)) {
    jj_scanpos = xsp;
    if (jj_scan_token(24)) {
    jj_scanpos = xsp;
    if (jj_scan_token(23)) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_46()
 {
    if (jj_scan_token(SWITCH)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_45()
 {
    if (jj_scan_token(CONTINUE)) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  private boolean jj_3_16()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(DOT)) return true;
    return false;
  }

  private boolean jj_3R_44()
 {
    if (jj_scan_token(BREAK)) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  private boolean jj_3R_43()
 {
    if (jj_scan_token(LBRACE)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_51()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3R_51()
 {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_42()
 {
    if (jj_scan_token(RETURN)) return true;
    if (jj_3R_50()) return true;
    return false;
  }

  private boolean jj_3R_57()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_20()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  private boolean jj_3R_59()
 {
    if (jj_scan_token(DOT)) return true;
    return false;
  }

  private boolean jj_3R_19()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  private boolean jj_3R_22()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  private boolean jj_3_11()
 {
    if (jj_3R_18()) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_21()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  private boolean jj_3R_56()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    Token xsp;
    if (jj_3R_59()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_59()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_6()
 {
    if (jj_scan_token(VOID)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_81()
 {
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    if (jj_3R_18()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_22()) jj_scanpos = xsp;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_15()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_3R_18()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_21()) jj_scanpos = xsp;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  private boolean jj_3_14()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(DOT)) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_3R_17()) return true;
    if (jj_scan_token(VOID)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_3R_17()) return true;
    if (jj_3R_18()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_20()) jj_scanpos = xsp;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_17()) return true;
    if (jj_3R_18()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_19()) jj_scanpos = xsp;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  private boolean jj_3R_80()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_79()
 {
    if (jj_3R_57()) return true;
    return false;
  }

  private boolean jj_3R_78()
 {
    if (jj_3R_56()) return true;
    return false;
  }

  private boolean jj_3R_77()
 {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  private boolean jj_3R_76()
 {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  private boolean jj_3R_75()
 {
    if (jj_scan_token(CHAR_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_74()
 {
    if (jj_scan_token(STRING_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_39()
 {
    if (jj_scan_token(FOR)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_73()
 {
    if (jj_scan_token(DOUBLE_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_72()
 {
    if (jj_scan_token(FLOAT_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_71()
 {
    if (jj_scan_token(LONG_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_70()
 {
    if (jj_scan_token(INTEGER_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_69()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_70()) {
    jj_scanpos = xsp;
    if (jj_3R_71()) {
    jj_scanpos = xsp;
    if (jj_3R_72()) {
    jj_scanpos = xsp;
    if (jj_3R_73()) {
    jj_scanpos = xsp;
    if (jj_3R_74()) {
    jj_scanpos = xsp;
    if (jj_3R_75()) {
    jj_scanpos = xsp;
    if (jj_3R_76()) {
    jj_scanpos = xsp;
    if (jj_3R_77()) {
    jj_scanpos = xsp;
    if (jj_3R_78()) {
    jj_scanpos = xsp;
    if (jj_3R_79()) {
    jj_scanpos = xsp;
    if (jj_3R_80()) {
    jj_scanpos = xsp;
    if (jj_3R_81()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_41()
 {
    if (jj_scan_token(DO)) return true;
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_68()
 {
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  private boolean jj_3R_66()
 {
    if (jj_3R_69()) return true;
    return false;
  }

  private boolean jj_3R_67()
 {
    if (jj_scan_token(NOT)) return true;
    return false;
  }

  private boolean jj_3R_65()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_67()) {
    jj_scanpos = xsp;
    if (jj_3R_68()) return true;
    }
    return false;
  }

  private boolean jj_3R_64()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_65()) {
    jj_scanpos = xsp;
    if (jj_3R_66()) return true;
    }
    return false;
  }

  private boolean jj_3R_40()
 {
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_63()
 {
    if (jj_3R_64()) return true;
    return false;
  }

  private boolean jj_3R_38()
 {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_48()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_62()
 {
    if (jj_3R_63()) return true;
    return false;
  }

  private boolean jj_3R_61()
 {
    if (jj_3R_62()) return true;
    return false;
  }

  private boolean jj_3R_47()
 {
    if (jj_3R_18()) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_10()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_9()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(DOT)) return true;
    return false;
  }

  private boolean jj_3R_60()
 {
    if (jj_3R_61()) return true;
    return false;
  }

  private boolean jj_3_8()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_54()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_23()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  private boolean jj_3R_53()
 {
    if (jj_3R_57()) return true;
    return false;
  }

  private boolean jj_3R_58()
 {
    if (jj_3R_60()) return true;
    return false;
  }

  private boolean jj_3R_52()
 {
    if (jj_3R_56()) return true;
    return false;
  }

  private boolean jj_3_7()
 {
    if (jj_3R_18()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_23()) jj_scanpos = xsp;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_36()
 {
    if (jj_3R_48()) return true;
    return false;
  }

  private boolean jj_3R_55()
 {
    if (jj_3R_58()) return true;
    return false;
  }

  private boolean jj_3R_37()
 {
    if (jj_3R_49()) return true;
    return false;
  }

  private boolean jj_3R_49()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) return true;
    }
    }
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public JavaParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[47];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x8e00,0x3ff8e00,0x8e00,0x0,0x8e00,0x3ff0000,0x3fe0000,0xf7fe0000,0x0,0x0,0x3fe0000,0x8e00,0x8e00,0xf4000000,0x0,0x0,0x0,0x8000000,0x3fe0000,0x0,0x0,0x0,0x0,0xf7fe0000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x40000000,0x0,0x0,0x0,0x10000070,0x0,0x40000000,0x0,0x0,0x0,0x10000070,0x0,0x0,0x200,0x0,0x0,0x4800803,0x0,0x0,0x200,0x10000070,0x80,0x100,0x0,0x400000,0x200000,0x18000,0x18000,0x1e0000,0x1e0000,0xc00,0xc00,0x3000,0x3000,0x800800,0x4800803,0x3,0x4000000,0x4800803,0x4000000,0x0,0x4800803,0x0,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1000,0x2,0x0,0x0,0x0,0x0,0x0,0x1000,0x1000,0x0,0x0,0x1000,0x13f0,0x1000,0x1000,0x0,0x1000,0x0,0x0,0x1310,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x13f0,0x3f0,0x1000,0x13f0,0x0,0x4,0x13f0,0x1000,0x2,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[16];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public JavaParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public JavaParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new JavaParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 47; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 47; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public JavaParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new JavaParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 47; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 47; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public JavaParser(JavaParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 47; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(JavaParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 47; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[77];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 47; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 77; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 16; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
