/* Generated By:JavaCC: Do not edit this line. JavaParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int CLASS = 8;
  /** RegularExpression Id. */
  int PUBLIC = 9;
  /** RegularExpression Id. */
  int PRIVATE = 10;
  /** RegularExpression Id. */
  int PROTECTED = 11;
  /** RegularExpression Id. */
  int FINAL = 12;
  /** RegularExpression Id. */
  int ABSTRACT = 13;
  /** RegularExpression Id. */
  int CONST = 14;
  /** RegularExpression Id. */
  int STATIC = 15;
  /** RegularExpression Id. */
  int VOID = 16;
  /** RegularExpression Id. */
  int INT = 17;
  /** RegularExpression Id. */
  int LONG = 18;
  /** RegularExpression Id. */
  int SHORT = 19;
  /** RegularExpression Id. */
  int BYTE = 20;
  /** RegularExpression Id. */
  int FLOAT = 21;
  /** RegularExpression Id. */
  int DOUBLE = 22;
  /** RegularExpression Id. */
  int STRING = 23;
  /** RegularExpression Id. */
  int CHAR = 24;
  /** RegularExpression Id. */
  int BOOLEAN = 25;
  /** RegularExpression Id. */
  int IF = 26;
  /** RegularExpression Id. */
  int ELSE = 27;
  /** RegularExpression Id. */
  int WHILE = 28;
  /** RegularExpression Id. */
  int DO = 29;
  /** RegularExpression Id. */
  int FOR = 30;
  /** RegularExpression Id. */
  int RETURN = 31;
  /** RegularExpression Id. */
  int TRUE = 32;
  /** RegularExpression Id. */
  int FALSE = 33;
  /** RegularExpression Id. */
  int NEW = 34;
  /** RegularExpression Id. */
  int THIS = 35;
  /** RegularExpression Id. */
  int BREAK = 36;
  /** RegularExpression Id. */
  int CONTINUE = 37;
  /** RegularExpression Id. */
  int SWITCH = 38;
  /** RegularExpression Id. */
  int CASE = 39;
  /** RegularExpression Id. */
  int DEFAULt = 40;
  /** RegularExpression Id. */
  int ASSIGN = 41;
  /** RegularExpression Id. */
  int PLUS = 42;
  /** RegularExpression Id. */
  int MINUS = 43;
  /** RegularExpression Id. */
  int DIVIDE = 44;
  /** RegularExpression Id. */
  int MULTIPLY = 45;
  /** RegularExpression Id. */
  int MODULO = 46;
  /** RegularExpression Id. */
  int EQ = 47;
  /** RegularExpression Id. */
  int NE = 48;
  /** RegularExpression Id. */
  int LT = 49;
  /** RegularExpression Id. */
  int LE = 50;
  /** RegularExpression Id. */
  int GT = 51;
  /** RegularExpression Id. */
  int GE = 52;
  /** RegularExpression Id. */
  int AND = 53;
  /** RegularExpression Id. */
  int OR = 54;
  /** RegularExpression Id. */
  int NOT = 55;
  /** RegularExpression Id. */
  int INCREMENT = 56;
  /** RegularExpression Id. */
  int DECREMENT = 57;
  /** RegularExpression Id. */
  int LPAREN = 58;
  /** RegularExpression Id. */
  int RPAREN = 59;
  /** RegularExpression Id. */
  int LBRACE = 60;
  /** RegularExpression Id. */
  int RBRACE = 61;
  /** RegularExpression Id. */
  int LBRACKET = 62;
  /** RegularExpression Id. */
  int RBRACKET = 63;
  /** RegularExpression Id. */
  int SEMICOLON = 64;
  /** RegularExpression Id. */
  int COMMA = 65;
  /** RegularExpression Id. */
  int DOT = 66;
  /** RegularExpression Id. */
  int COLON = 67;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 68;
  /** RegularExpression Id. */
  int LONG_LITERAL = 69;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 70;
  /** RegularExpression Id. */
  int DOUBLE_LITERAL = 71;
  /** RegularExpression Id. */
  int STRING_LITERAL = 72;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 73;
  /** RegularExpression Id. */
  int BOOLEAN_LITERAL = 74;
  /** RegularExpression Id. */
  int NULL_LITERAL = 75;
  /** RegularExpression Id. */
  int IDENTIFIER = 76;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"class\"",
    "\"public\"",
    "\"private\"",
    "\"protected\"",
    "\"final\"",
    "\"abstract\"",
    "\"const\"",
    "\"static\"",
    "\"void\"",
    "\"int\"",
    "\"long\"",
    "\"short\"",
    "\"byte\"",
    "\"float\"",
    "\"double\"",
    "\"String\"",
    "\"char\"",
    "\"boolean\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "\"new\"",
    "\"this\"",
    "\"break\"",
    "\"continue\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"%\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"++\"",
    "\"--\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "<INTEGER_LITERAL>",
    "<LONG_LITERAL>",
    "<FLOAT_LITERAL>",
    "<DOUBLE_LITERAL>",
    "<STRING_LITERAL>",
    "<CHAR_LITERAL>",
    "<BOOLEAN_LITERAL>",
    "\"null\"",
    "<IDENTIFIER>",
  };

}
