/* JavaParser.java */
/* Generated By:JavaCC: Do not edit this line. JavaParser.java */
package parser;
import parser.SymbolTable;import java.util.*;
import java.io.*;
import parser.ASTNode;

public class JavaParser implements JavaParserConstants {
    // Use external parser.SymbolTable class
    private SymbolTable symbolTable = new SymbolTable();

    // Helper method to get clean token name
    private String getTokenName(Token token) {
        String name = tokenImage[token.kind];
            if (name.equals("\u005c"<\u005c"") || name.equals("\u005c">\u005c"") || name.equals("\u005c"<=\u005c"") || name.equals("\u005c">=\u005c"")) {
                return "Operator";  // Keep the operator as is (without any cleaning)
            }
        name = name.replace("\u005c"", "").replace("<","").replace(">","") ;

        // Map to token type names
    switch (name) {
            case "class": case "public": case "private": case"protected":
            case"final": case"const": case "static": case "void": case "int":
            case "double": case "float": case "long": case "short": case "byte":
            case "char": case "boolean": case "if": case "else": case "while": case "do":
            case "for": case "return": case "break": case "continue": case "true": case "false":
            case "switch": case "case" : case "default":
                return "Keyword";

            case "=": case "+": case "-": case "*": case "/": case "%": case "==": case "!=": case "<":
            case ">": case "<=": case ">=": case "&&": case "||": case "!": case "++": case "--":
                return "Operator";

            case "(": case ")": case "{": case "}": case "[":
            case "]": case ";": case ",": case ".": case ":":
                return "Special character";

            case "SINGLE_LINE_COMMENT":
            case "MULTI_LINE_COMMENT":
                return "Comment";

            case "STRING_LITERAL":
            case "CHAR_LITERAL":
                return "Character Constant";

            case "INTEGER_LITERAL":
            case "LONG_LITERAL":
            case "FLOAT_LITERAL":
            case "DOUBLE_LITERAL":
                return "Numeric Constant";

            default:
                return name;
        }
    }
    private void recordSpecialTokens(Token t) {
        Token special = t.specialToken;
        while (special != null) {
            symbolTable.addToken(special, "Comment");
            special = special.specialToken;
        }
    }
    private void recordToken(Token t) {
        recordSpecialTokens(t);
        symbolTable.addToken(t, getTokenName(t));
    }

    public void printSymbolTable() {
        symbolTable.printSymbolTable();
    }

    public List<String> getUnusedVariables() {
        return symbolTable.getUnusedVariables();
        }

    public static void main(String[] args) {
        // Check if filename argument is provided

        // if (args.length < 1) {
        //     System.err.println("Usage: java Main <input_file.java>");
        //     System.exit(1);
        // }

        // String filename = args[0];
        String filename = "D:/root/temp/faculty/compiler/repos/compiler-project/input/valid.txt";

        try {

            System.out.println("Input file: " + filename);
            System.out.println();

            // Create parser with input file
            FileInputStream fis = new FileInputStream(filename);
            JavaParser parser = new JavaParser(fis);

            ASTNode ast = parser.Program();

            System.out.println();
            System.out.println("SYNTAX VALIDATION SUCCESSFUL!");
            System.out.println();



            // Display symbol table (Phase 1)

            parser.printSymbolTable();
            System.out.println();

            // Display AST (Phase 3)
            System.out.println("========================================");
            System.out.println("ABSTRACT SYNTAX TREE (AST)");
            System.out.println("========================================");
            ast.print(0);
            ast.printTree("",true);
            System.out.println();
            // Check for unused variables
            System.out.println("========================================");
            TypeChecker typeChecker = new TypeChecker(parser.symbolTable);
            typeChecker.analyze(ast);
            typeChecker.printResults();
            System.out.println();
            java.util.List<String> unused = parser.getUnusedVariables();
            if (!unused.isEmpty()) {
                System.out.println("========================================");
                System.out.println("WARNINGS: UNUSED VARIABLES");
                System.out.println("========================================");
                for (String var : unused) {
                    System.out.println(" -> " + var);
                }
                System.out.println();
            }

            // Close the input stream
            fis.close();

            // Summary

            System.out.println("Phase 1 (Lexical Analysis): Complete");
            System.out.println("Phase 2 (Syntax Analysis): Complete");
            System.out.println("No syntax errors detected");
            System.out.println();

        } catch (FileNotFoundException e) {
            System.err.println("\u00e2\u0153\u2014 ERROR: File '" + filename + "' not found.");
            System.exit(1);

        } catch (ParseException e) {
            // Handle syntax errors
            System.err.println();
            System.err.println("\u00e2\u2022\u201d\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\u2014");
            System.err.println("\u00e2\u2022\u2018    SYNTAX ERROR DETECTED               \u00e2\u2022\u2018");
            System.err.println("\u00e2\u2022\u0161\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd");
            System.err.println();
            System.err.println("Location: Line " + e.currentToken.next.beginLine +
                    ", Column " + e.currentToken.next.beginColumn);
            System.err.println();

            // Display error message
            System.err.println("Error Message:");
            System.err.println("  " + e.getMessage());
            System.err.println();

            // Try to provide more helpful context
            if (e.currentToken != null && e.currentToken.next != null) {
                System.err.println("Unexpected token: \u005c"" + e.currentToken.next.image + "\u005c"");
                System.err.println();
            }

            System.exit(1);

        } catch (TokenMgrError e) {
            // Handle lexical errors (invalid tokens)
            System.err.println();
            System.err.println("\u00e2\u2022\u201d\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\u2014");
            System.err.println("\u00e2\u2022\u2018   \u00e2\u0153\u2014 LEXICAL ERROR DETECTED             \u00e2\u2022\u2018");
            System.err.println("\u00e2\u2022\u0161\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd\u00e2\u2022\ufffd");
            System.err.println();
            System.err.println("Invalid token or character encountered");
            System.err.println();
            System.err.println("Error Message:");
            System.err.println("  " + e.getMessage());
            System.err.println();
            System.exit(1);

        } catch (IOException e) {
            System.err.println("\u00e2\u0153\u2014 ERROR: Could not read file: " + e.getMessage());
            System.exit(1);

        }catch ( RuntimeException e)
        {
            System.err.println(e.getMessage());
            System.exit(1);
        }catch (Exception e) {
            System.err.println("\u00e2\u0153\u2014 UNEXPECTED ERROR: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        }
    }

///=====================phase2:parsing====================///
  final public 
ASTNode Program() throws ParseException {ASTNode classDecl;
 ProgrameNode program = new ProgrameNode();
symbolTable.enterScope();
    //TODO (kaizen) #12
    
    classDecl = ClassDeclaration();
program.addClass(classDecl);
symbolTable.exitScope();
    jj_consume_token(0);
{if ("" != null) return program;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode ClassDeclaration() throws ParseException {Token tCLASS,className,tRBRACE,tLBRACE;
        String modifiers = "";
        ClassNode classNode;
        ASTNode member;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PUBLIC:
    case PRIVATE:
    case PROTECTED:
    case STATIC:{
      modifiers = Modifiers();
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    tCLASS = jj_consume_token(CLASS);
    //* class
     className = jj_consume_token(IDENTIFIER);
recordToken(tCLASS);
recordToken(className);
        classNode = new ClassNode(className.image,modifiers, className.beginLine, className.beginColumn);
symbolTable.enterScope();
    //TODO (kaizen) #12
    tLBRACE = jj_consume_token(LBRACE);
recordToken(tLBRACE);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUBLIC:
      case PRIVATE:
      case PROTECTED:
      case STATIC:
      case VOID:
      case INT:
      case LONG:
      case SHORT:
      case BYTE:
      case FLOAT:
      case DOUBLE:
      case STRING:
      case CHAR:
      case BOOLEAN:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      member = MemberDeclaration();
classNode.addMember(member);
    }
    tRBRACE = jj_consume_token(RBRACE);
symbolTable.exitScope();
recordToken(tRBRACE);
 {if ("" != null) return classNode;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode MemberDeclaration() throws ParseException {ASTNode node;
    if (jj_2_1(2147483647)) {
      node = FieldDeclaration();
    } else if (jj_2_2(2147483647)) {
      node = MethodDeclaration();
    } else if (jj_2_3(2147483647)) {
      node = MethodDeclaration();
    } else if (jj_2_4(2147483647)) {
      node = FieldDeclaration();
    } else if (jj_2_5(2147483647)) {
      node = MethodDeclaration();
    } else if (jj_2_6(2147483647)) {
      node = MethodDeclaration();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode FieldDeclaration() throws ParseException {Token type,id,tSEMICOLON,tLBRACKET,tRBRACKET;
        String modifiers = "";
            boolean isArray = false;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PUBLIC:
    case PRIVATE:
    case PROTECTED:
    case STATIC:{
      modifiers = Modifiers();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    type = Type();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LBRACKET:{
      tLBRACKET = jj_consume_token(LBRACKET);
      tRBRACKET = jj_consume_token(RBRACKET);
recordToken(tLBRACKET);
                                                        recordToken(tRBRACKET);
                                                        isArray = true;
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    id = jj_consume_token(IDENTIFIER);
    tSEMICOLON = jj_consume_token(SEMICOLON);
recordToken(type);
    recordToken(id);
    recordToken(tSEMICOLON);
    symbolTable.addVariable(id.image,type.image,id.beginLine);
    {if ("" != null) return new FieldNode(modifiers, type.image, id.image, isArray, id.beginLine, id.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode MethodDeclaration() throws ParseException {Token returnType,methodName,tRBRACE,tLBRACE,tLPAREN,tRPAREN;
    String modifiers = "";
    MethodNode methodNode ;
    List<ASTNode> params = new ArrayList<ASTNode>();
    List<ASTNode> statements = new ArrayList<ASTNode>();
    ASTNode param, stmt;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PUBLIC:
    case PRIVATE:
    case PROTECTED:
    case STATIC:{
      modifiers = Modifiers();
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:
    case LONG:
    case SHORT:
    case BYTE:
    case FLOAT:
    case DOUBLE:
    case STRING:
    case CHAR:
    case BOOLEAN:{
      returnType = Type();
      break;
      }
    case VOID:{
      returnType = jj_consume_token(VOID);
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
recordToken(returnType);
    methodName = jj_consume_token(IDENTIFIER);
recordToken(methodName);
        methodNode = new MethodNode(modifiers, returnType.image, methodName.image,
                                            methodName.beginLine, methodName.beginColumn);
symbolTable.enterScope();
    //TODO (kaizen) #12
    
        tLPAREN = jj_consume_token(LPAREN);
recordToken(tLPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:
    case LONG:
    case SHORT:
    case BYTE:
    case FLOAT:
    case DOUBLE:
    case STRING:
    case CHAR:
    case BOOLEAN:{
      param = Parameter();
params.add(param);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          break label_2;
        }
        jj_consume_token(COMMA);
        param = Parameter();
params.add(param);
      }
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
    tRPAREN = jj_consume_token(RPAREN);
recordToken(tRPAREN);
    //* )
        tLBRACE = jj_consume_token(LBRACE);
recordToken(tLBRACE);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:
      case LONG:
      case SHORT:
      case BYTE:
      case FLOAT:
      case DOUBLE:
      case STRING:
      case CHAR:
      case BOOLEAN:
      case IF:
      case WHILE:
      case DO:
      case FOR:
      case RETURN:
      case TRUE:
      case FALSE:
      case BREAK:
      case CONTINUE:
      case SWITCH:
      case INCREMENT:
      case DECREMENT:
      case LPAREN:
      case LBRACE:
      case INTEGER_LITERAL:
      case LONG_LITERAL:
      case FLOAT_LITERAL:
      case DOUBLE_LITERAL:
      case STRING_LITERAL:
      case CHAR_LITERAL:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_3;
      }
      stmt = Statement();
statements.add(stmt);
    }
    tRBRACE = jj_consume_token(RBRACE);
//* }
    {symbolTable.exitScope();}//TODO (kaizen) #12
       recordToken(tRBRACE);
       methodNode.setParameter(params);
       methodNode.setStatement(statements);
       {if ("" != null) return methodNode;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode Parameter() throws ParseException {Token type,id,tLBRACKET,tRBRACKET;
    boolean isArray = false;
    type = Type();
recordToken(type);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LBRACKET:{
      tLBRACKET = jj_consume_token(LBRACKET);
      tRBRACKET = jj_consume_token(RBRACKET);
recordToken(tLBRACKET);
        recordToken(tRBRACKET);
        isArray=true;
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    // Optional array brackets
      id = jj_consume_token(IDENTIFIER);
recordToken(id);
        symbolTable.addVariable(id.image,type.image,id.beginLine);
        {if ("" != null) return new ParameterNode(type.image, id.image, isArray, id.beginLine, id.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  final public Token Type() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:{
      t = jj_consume_token(INT);
      break;
      }
    case LONG:{
      t = jj_consume_token(LONG);
      break;
      }
    case SHORT:{
      t = jj_consume_token(SHORT);
      break;
      }
    case BYTE:{
      t = jj_consume_token(BYTE);
      break;
      }
    case DOUBLE:{
      t = jj_consume_token(DOUBLE);
      break;
      }
    case FLOAT:{
      t = jj_consume_token(FLOAT);
      break;
      }
    case BOOLEAN:{
      t = jj_consume_token(BOOLEAN);
      break;
      }
    case CHAR:{
      t = jj_consume_token(CHAR);
      break;
      }
    case STRING:{
      t = jj_consume_token(STRING);
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return t;}
    throw new Error("Missing return statement in function");
  }

  final public String Modifiers() throws ParseException {Token mod;
    List<String> modList = new ArrayList<String>();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUBLIC:{
        mod = jj_consume_token(PUBLIC);
        break;
        }
      case PRIVATE:{
        mod = jj_consume_token(PRIVATE);
        break;
        }
      case PROTECTED:{
        mod = jj_consume_token(PROTECTED);
        break;
        }
      case STATIC:{
        mod = jj_consume_token(STATIC);
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
recordToken(mod);
            modList.add(mod.image);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUBLIC:
      case PRIVATE:
      case PROTECTED:
      case STATIC:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_4;
      }
    }
{if ("" != null) return String.join(" ", modList);}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode Statement() throws ParseException {ASTNode node;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IF:{
      node = IfStatement();
      break;
      }
    case FOR:{
      node = ForStatement();
      break;
      }
    case WHILE:{
      node = WhileStatement();
      break;
      }
    case DO:{
      node = DoWhileStatement();
      break;
      }
    case RETURN:{
      node = ReturnStatement();
      break;
      }
    case LBRACE:{
      node = Block();
      break;
      }
    case BREAK:{
      node = BreakStatement();
      break;
      }
    case CONTINUE:{
      node = ContinueStatement();
      break;
      }
    case SWITCH:{
      node = SwitchStatement();
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      if (jj_2_7(2147483647)) {
        node = VariableDeclaration();
      } else if (jj_2_8(2147483647)) {
        node = AssignmentStatement();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TRUE:
        case FALSE:
        case INCREMENT:
        case DECREMENT:
        case LPAREN:
        case INTEGER_LITERAL:
        case LONG_LITERAL:
        case FLOAT_LITERAL:
        case DOUBLE_LITERAL:
        case STRING_LITERAL:
        case CHAR_LITERAL:
        case IDENTIFIER:{
          node = StatementExpression();
          break;
          }
        default:
          jj_la1[14] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode StatementExpression() throws ParseException {ASTNode node;
     Token tSEMICOLON;
    if (jj_2_9(2147483647)) {
      node = MemberAccess();
    } else if (jj_2_10(2147483647)) {
      node = MethodCall();
    } else if (jj_2_11(2147483647)) {
      node = PostIncrementExpressionWithoutSemicolon();
    } else if (jj_2_12(2147483647)) {
      node = PostDecrementExpressionWithoutSemicolon();
    } else if (jj_2_13(2147483647)) {
      node = PreIncrementExpressionWithoutSemicolon();
    } else if (jj_2_14(2147483647)) {
      node = PreDecrementExpressionWithoutSemicolon();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TRUE:
      case FALSE:
      case LPAREN:
      case INTEGER_LITERAL:
      case LONG_LITERAL:
      case FLOAT_LITERAL:
      case DOUBLE_LITERAL:
      case STRING_LITERAL:
      case CHAR_LITERAL:
      case IDENTIFIER:{
        node = PrimaryExpression();
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    tSEMICOLON = jj_consume_token(SEMICOLON);
recordToken(tSEMICOLON);
     {if ("" != null) return node;}
    throw new Error("Missing return statement in function");
  }

//* int []x = expression ;
//* int y = expression;
  final public ASTNode VariableDeclaration() throws ParseException {Token type, id, tAssign, tSEMICOLON, tLBRACKET, tRBRACKET;
    boolean isArray = false;
    ASTNode initializer = null;
    type = Type();
recordToken(type);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LBRACKET:{
      tLBRACKET = jj_consume_token(LBRACKET);
      tRBRACKET = jj_consume_token(RBRACKET);
recordToken(tLBRACKET);
         recordToken(tRBRACKET);
         isArray = true;
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
    id = jj_consume_token(IDENTIFIER);
recordToken(id);
         symbolTable.addVariable(id.image, type.image, id.beginLine);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASSIGN:{
      tAssign = jj_consume_token(ASSIGN);
recordToken(tAssign);
      initializer = Expression();
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    tSEMICOLON = jj_consume_token(SEMICOLON);
recordToken(tSEMICOLON);
         {if ("" != null) return new VariableDeclarationNode(type.image, id.image, isArray, initializer,
                                          id.beginLine, id.beginColumn);}
    throw new Error("Missing return statement in function");
  }

//* id = expression ;
  final public ASTNode AssignmentStatement() throws ParseException {Token id,tAssign,tSEMICOLON;
            ASTNode expr;
    id = jj_consume_token(IDENTIFIER);
    tAssign = jj_consume_token(ASSIGN);
recordToken(id);
            recordToken(tAssign);
                 if (!symbolTable.isVariableDeclared(id.image)) {
                     {if (true) throw new RuntimeException ("Semantic Error: Variable '" + id.image +
                                                     "' used before declaration at line " + id.beginLine) ;}
                 } else {
                    {System.out.println("Debugging [ id = " + (id.image) + " ]");}
                     symbolTable.markVariableUsed(id.image);
                 }
    expr = Expression();
    tSEMICOLON = jj_consume_token(SEMICOLON);
recordToken(tSEMICOLON);
         {if ("" != null) return new AssignmentNode(id.image, expr, id.beginLine, id.beginColumn);}
    throw new Error("Missing return statement in function");
  }

//* 
  final public ASTNode IfStatement() throws ParseException {Token tIf,tElse,tLPAREN,tRPAREN;
            ASTNode condition, thenStmt, elseStmt = null;
    tIf = jj_consume_token(IF);
recordToken(tIf);
    tLPAREN = jj_consume_token(LPAREN);
recordToken(tLPAREN);
    //* (
        condition = Expression();
    //* x > 5
        tRPAREN = jj_consume_token(RPAREN);
recordToken(tRPAREN);
    //* )
        // thenStmt = Statement() 
        thenStmt = Block();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      tElse = jj_consume_token(ELSE);
recordToken(tElse);
      elseStmt = Block();
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      ;
    }
{if ("" != null) return new IfNode(condition, thenStmt, elseStmt, tIf.beginLine, tIf.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode WhileStatement() throws ParseException {Token t,tLPAREN,tRPAREN;
            ASTNode condition, body;
    t = jj_consume_token(WHILE);
recordToken(t);
    tLPAREN = jj_consume_token(LPAREN);
recordToken(tLPAREN);
    condition = Expression();
    tRPAREN = jj_consume_token(RPAREN);
recordToken(tRPAREN);
    body = Block();
{if ("" != null) return new WhileNode(condition, body, t.beginLine, t.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode DoWhileStatement() throws ParseException {Token tDo,tWhile,tLPAREN,tRPAREN,tSEMI;
        ASTNode body, condition;
    tDo = jj_consume_token(DO);
recordToken(tDo);
    body = Block();
    //TODO (kaizen) #13
        tWhile = jj_consume_token(WHILE);
recordToken(tWhile);
    //* while
        tLPAREN = jj_consume_token(LPAREN);
recordToken(tLPAREN);
    //* (
        condition = Expression();
    //* x>5
        tRPAREN = jj_consume_token(RPAREN);
    //* ) 
        tSEMI = jj_consume_token(SEMICOLON);
recordToken(tRPAREN);
        recordToken(tSEMI);
        {if ("" != null) return new DoWhileNode(condition, body, tDo.beginLine, tDo.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode ForStatement() throws ParseException {Token t,tLPAREN,tRPAREN,tSEMICOLON;
        ASTNode init = null, condition = null, update = null, body;
    t = jj_consume_token(FOR);
recordToken(t);
    tLPAREN = jj_consume_token(LPAREN);
recordToken(tLPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:
    case LONG:
    case SHORT:
    case BYTE:
    case FLOAT:
    case DOUBLE:
    case STRING:
    case CHAR:
    case BOOLEAN:
    case IDENTIFIER:{
      init = ForInit();
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      ;
    }
    //* int i = 0; || i = 0
         tSEMICOLON = jj_consume_token(SEMICOLON);
recordToken(tSEMICOLON);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TRUE:
    case FALSE:
    case MINUS:
    case NOT:
    case LPAREN:
    case INTEGER_LITERAL:
    case LONG_LITERAL:
    case FLOAT_LITERAL:
    case DOUBLE_LITERAL:
    case STRING_LITERAL:
    case CHAR_LITERAL:
    case IDENTIFIER:{
      condition = Expression();
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      ;
    }
    tSEMICOLON = jj_consume_token(SEMICOLON);
recordToken(tSEMICOLON);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INCREMENT:
    case DECREMENT:
    case IDENTIFIER:{
      update = ForUpdate();
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      ;
    }
    tRPAREN = jj_consume_token(RPAREN);
recordToken(tRPAREN);
    body = Statement();
{if ("" != null) return new ForNode(init, condition, update, body, t.beginLine, t.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode ForInit() throws ParseException {ASTNode node;
    if (jj_2_15(2147483647)) {
      //* x
          node = VariableDeclarationWithoutSemicolon();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        node = AssignmentWithoutSemicolon();
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return node ;}
    throw new Error("Missing return statement in function");
  }

//* int x || int x = expression
  final public ASTNode VariableDeclarationWithoutSemicolon() throws ParseException {Token type, id,tAssign;
    ASTNode initializer = null;
    type = Type();
    id = jj_consume_token(IDENTIFIER);
recordToken(type);
        recordToken(id);
        symbolTable.addVariable(id.image, type.image, id.beginLine);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASSIGN:{
      tAssign = jj_consume_token(ASSIGN);
recordToken(tAssign);
      initializer = Expression();
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      ;
    }
{if ("" != null) return new VariableDeclarationNode(type.image, id.image, false, initializer,
                                          id.beginLine, id.beginColumn);}
    throw new Error("Missing return statement in function");
  }

//* x = expression
  final public ASTNode AssignmentWithoutSemicolon() throws ParseException {Token id,tAssign;
    ASTNode expr;
    id = jj_consume_token(IDENTIFIER);
recordToken(id);
        symbolTable.markVariableUsed(id.image);
    tAssign = jj_consume_token(ASSIGN);
recordToken(tAssign);
    expr = Expression();
{if ("" != null) return new AssignmentNode(id.image, expr, id.beginLine, id.beginColumn);}
    throw new Error("Missing return statement in function");
  }

//* --------------------------------------
//* x = 
//* x ++
//* x --
//* ++ x
//* -- x
  final public ASTNode ForUpdate() throws ParseException {ASTNode node;
    if (jj_2_16(2147483647)) {
      node = AssignmentWithoutSemicolon();
    } else if (jj_2_17(2147483647)) {
      node = PostIncrementExpressionWithoutSemicolon();
    } else if (jj_2_18(2147483647)) {
      node = PostDecrementExpressionWithoutSemicolon();
    } else if (jj_2_19(2147483647)) {
      node = PreIncrementExpressionWithoutSemicolon();
    } else if (jj_2_20(2147483647)) {
      node = PreDecrementExpressionWithoutSemicolon();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
  }

//* --------------------------------------
//* x++
  final public ASTNode PostIncrementExpressionWithoutSemicolon() throws ParseException {Token id,tINC;
    id = jj_consume_token(IDENTIFIER);
    tINC = jj_consume_token(INCREMENT);
recordToken(id);
        recordToken(tINC);
        symbolTable.markVariableUsed(id.image);
        {if ("" != null) return new UnaryOpNode("++", new IdentifierNode(id.image, id.beginLine, id.beginColumn),
                               false, id.beginLine, id.beginColumn);}
    throw new Error("Missing return statement in function");
  }

//* x--
  final public ASTNode PostDecrementExpressionWithoutSemicolon() throws ParseException {Token id,tDEC;
    id = jj_consume_token(IDENTIFIER);
    tDEC = jj_consume_token(DECREMENT);
recordToken(id);
        recordToken(tDEC);
        symbolTable.markVariableUsed(id.image);
        {if ("" != null) return new UnaryOpNode("--", new IdentifierNode(id.image, id.beginLine, id.beginColumn),
                               false, id.beginLine, id.beginColumn);}
    throw new Error("Missing return statement in function");
  }

//* ++x
  final public ASTNode PreIncrementExpressionWithoutSemicolon() throws ParseException {Token id,tINC;
    tINC = jj_consume_token(INCREMENT);
    id = jj_consume_token(IDENTIFIER);
recordToken(tINC);
        recordToken(id);
        symbolTable.markVariableUsed(id.image);
        {if ("" != null) return new UnaryOpNode("++", new IdentifierNode(id.image, id.beginLine, id.beginColumn),
                               true, id.beginLine, id.beginColumn);}
    throw new Error("Missing return statement in function");
  }

//* --x
  final public ASTNode PreDecrementExpressionWithoutSemicolon() throws ParseException {Token id,tDEC;
    tDEC = jj_consume_token(DECREMENT);
    id = jj_consume_token(IDENTIFIER);
recordToken(tDEC);
        recordToken(id);
        symbolTable.markVariableUsed(id.image);
        {if ("" != null) return new UnaryOpNode("--", new IdentifierNode(id.image, id.beginLine, id.beginColumn),
                                      true, id.beginLine, id.beginColumn);}
    throw new Error("Missing return statement in function");
  }

//* --------------------------------------

//* return expression ;
  final public ASTNode ReturnStatement() throws ParseException {Token t,tSEMICOLON;
    ASTNode expr;
    t = jj_consume_token(RETURN);
recordToken(t);
    expr = Expression();
    tSEMICOLON = jj_consume_token(SEMICOLON);
recordToken(tSEMICOLON);
        {if ("" != null) return new ReturnNode(expr, t.beginLine, t.beginColumn);}
    throw new Error("Missing return statement in function");
  }

//* --------------------------------------
  final public ASTNode Block() throws ParseException {Token tRBRACE,tLBRACE;
    List<ASTNode> statements = new ArrayList<ASTNode>();
    ASTNode stmt;
    tLBRACE = jj_consume_token(LBRACE);
recordToken(tLBRACE);
symbolTable.enterScope();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:
      case LONG:
      case SHORT:
      case BYTE:
      case FLOAT:
      case DOUBLE:
      case STRING:
      case CHAR:
      case BOOLEAN:
      case IF:
      case WHILE:
      case DO:
      case FOR:
      case RETURN:
      case TRUE:
      case FALSE:
      case BREAK:
      case CONTINUE:
      case SWITCH:
      case INCREMENT:
      case DECREMENT:
      case LPAREN:
      case LBRACE:
      case INTEGER_LITERAL:
      case LONG_LITERAL:
      case FLOAT_LITERAL:
      case DOUBLE_LITERAL:
      case STRING_LITERAL:
      case CHAR_LITERAL:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        break label_5;
      }
      stmt = Statement();
statements.add(stmt);
    }
    tRBRACE = jj_consume_token(RBRACE);
recordToken(tRBRACE);
        {if ("" != null) return new BlockNode(statements, tLBRACE.beginLine, tLBRACE.beginColumn);}
symbolTable.exitScope();
    throw new Error("Missing return statement in function");
  }

//* --------------------------------------

//* break ;
  final public ASTNode BreakStatement() throws ParseException {Token t,tSEMICOLON;
    t = jj_consume_token(BREAK);
recordToken(t);
    tSEMICOLON = jj_consume_token(SEMICOLON);
recordToken(tSEMICOLON);
        {if ("" != null) return new BreakNode(t.beginLine, t.beginColumn);}
    throw new Error("Missing return statement in function");
  }

//* continue ;
  final public ASTNode ContinueStatement() throws ParseException {Token t, tSEMICOLON;
    t = jj_consume_token(CONTINUE);
recordToken(t);
    tSEMICOLON = jj_consume_token(SEMICOLON);
recordToken(tSEMICOLON);
        {if ("" != null) return new ContinueNode(t.beginLine, t.beginColumn);}
    throw new Error("Missing return statement in function");
  }

//* switch ()
  final public ASTNode SwitchStatement() throws ParseException {Token t, tLPAREN, tRPAREN, tRBRACE, tLBRACE;
    ASTNode expr;
    SwitchNode switchNode;
    ASTNode caseNode, defaultNode = null;
    t = jj_consume_token(SWITCH);
recordToken(t);
    tLPAREN = jj_consume_token(LPAREN);
recordToken(tLPAREN);
    //* (
        expr = Expression();
    //* x
        tRPAREN = jj_consume_token(RPAREN);
recordToken(tRPAREN);
    //* )
        tLBRACE = jj_consume_token(LBRACE);
recordToken(tLBRACE);
        switchNode = new SwitchNode(expr, t.beginLine, t.beginColumn);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CASE:{
        ;
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        break label_6;
      }
      caseNode = SwitchCase();
switchNode.addCase(caseNode);
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DEFAULt:{
      defaultNode = DefaultCase();
switchNode.setDefaultCase(defaultNode);
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      ;
    }
    tRBRACE = jj_consume_token(RBRACE);
recordToken(tRBRACE);
        {if ("" != null) return switchNode;}
    throw new Error("Missing return statement in function");
  }

//* ---- switch ----------------------------
  final public 
ASTNode SwitchCase() throws ParseException {Token t, tCOLON, caseValue;
    CaseNode caseNode;
    ASTNode value, stmt;
    t = jj_consume_token(CASE);
recordToken(t);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER_LITERAL:{
      caseValue = jj_consume_token(INTEGER_LITERAL);
value = new LiteralNode("int", caseValue.image, caseValue.beginLine, caseValue.beginColumn);
      break;
      }
    case CHAR_LITERAL:{
      caseValue = jj_consume_token(CHAR_LITERAL);
value = new LiteralNode("char", caseValue.image, caseValue.beginLine, caseValue.beginColumn);
      break;
      }
    case STRING_LITERAL:{
      caseValue = jj_consume_token(STRING_LITERAL);
value = new LiteralNode("String", caseValue.image, caseValue.beginLine, caseValue.beginColumn);
      break;
      }
    case IDENTIFIER:{
      caseValue = jj_consume_token(IDENTIFIER);
value = new IdentifierNode(caseValue.image, caseValue.beginLine, caseValue.beginColumn);
      break;
      }
    default:
      jj_la1[27] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    tCOLON = jj_consume_token(COLON);
recordToken(tCOLON);
        caseNode = new CaseNode(value, t.beginLine, t.beginColumn);
    label_7:
    while (true) {
      if (getToken(1).kind != CASE && getToken(1).kind != DEFAULt && getToken(1).kind != RBRACE) {
        ;
      } else {
        break label_7;
      }
      stmt = Statement();
caseNode.addStatement(stmt);
    }
{if ("" != null) return caseNode;}
    throw new Error("Missing return statement in function");
  }

//* --------------------------------------
  final public 
ASTNode DefaultCase() throws ParseException {Token t, tCOLON;
    DefaultCaseNode defaultNode;
    ASTNode stmt;
    t = jj_consume_token(DEFAULt);
recordToken(t);
    tCOLON = jj_consume_token(COLON);
recordToken(tCOLON);
        defaultNode = new DefaultCaseNode(t.beginLine, t.beginColumn);
    label_8:
    while (true) {
      if (getToken(1).kind != RBRACE) {
        ;
      } else {
        break label_8;
      }
      stmt = Statement();
defaultNode.addStatement(stmt);
    }
{if ("" != null) return defaultNode;}
    throw new Error("Missing return statement in function");
  }

//* ((X==A) && Y) || Z
  final public ASTNode Expression() throws ParseException {ASTNode node;
    node = LogicalOrExpression();
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
  }

//* ((X==A) && Y) || Z
  final public ASTNode LogicalOrExpression() throws ParseException {Token t;
    ASTNode left, right;
    left = LogicalAndExpression();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        break label_9;
      }
      t = jj_consume_token(OR);
recordToken(t);
      right = LogicalAndExpression();
left = new BinaryOpNode("||", left, right, t.beginLine, t.beginColumn);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
  }

//* --------------------------------------

//* (X==A) && Y
  final public ASTNode LogicalAndExpression() throws ParseException {Token t;
        ASTNode left, right;
    left = EqualityExpression();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        ;
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        break label_10;
      }
      t = jj_consume_token(AND);
recordToken(t);
      right = EqualityExpression();
left = new BinaryOpNode("&&", left, right, t.beginLine, t.beginColumn);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
  }

//* --------------------------------------

//* X==A
  final public ASTNode EqualityExpression() throws ParseException {Token t;
    ASTNode left, right;
    left = RelationalExpression();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQ:
      case NE:{
        ;
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        break label_11;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQ:{
        t = jj_consume_token(EQ);
recordToken(t);
        break;
        }
      case NE:{
        t = jj_consume_token(NE);
recordToken(t);
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = RelationalExpression();
left = new BinaryOpNode(t.image, left, right, t.beginLine, t.beginColumn);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
  }

//* --------------------------------------

//*  (+, -) [<, <=, >, >= ] (+, -)
  final public ASTNode RelationalExpression() throws ParseException {Token t;
   ASTNode left, right;
    left = AdditiveExpression();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LT:
      case LE:
      case GT:
      case GE:{
        ;
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        break label_12;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LT:{
        t = jj_consume_token(LT);
recordToken(t);
        break;
        }
      case LE:{
        t = jj_consume_token(LE);
recordToken(t);
        break;
        }
      case GT:{
        t = jj_consume_token(GT);
recordToken(t);
        break;
        }
      case GE:{
        t = jj_consume_token(GE);
recordToken(t);
        break;
        }
      default:
        jj_la1[33] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = AdditiveExpression();
left = new BinaryOpNode(t.image, left, right, t.beginLine, t.beginColumn);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
  }

//* --------------------------------------
//* (+, -)
  final public ASTNode AdditiveExpression() throws ParseException {Token t;
   ASTNode left, right;
    left = MultiplicativeExpression();
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:{
        ;
        break;
        }
      default:
        jj_la1[34] = jj_gen;
        break label_13;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        t = jj_consume_token(PLUS);
recordToken(t);
        break;
        }
      case MINUS:{
        t = jj_consume_token(MINUS);
recordToken(t);
        break;
        }
      default:
        jj_la1[35] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = MultiplicativeExpression();
left = new BinaryOpNode(t.image, left, right, t.beginLine, t.beginColumn);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
  }

//*  (*, /)
  final public ASTNode MultiplicativeExpression() throws ParseException {Token t;
   ASTNode left, right;
    left = UnaryExpression();
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DIVIDE:
      case MULTIPLY:{
        ;
        break;
        }
      default:
        jj_la1[36] = jj_gen;
        break label_14;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLY:{
        t = jj_consume_token(MULTIPLY);
recordToken(t);
        break;
        }
      case DIVIDE:{
        t = jj_consume_token(DIVIDE);
recordToken(t);
        break;
        }
      default:
        jj_la1[37] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = UnaryExpression();
left = new BinaryOpNode(t.image, left, right, t.beginLine, t.beginColumn);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
  }

//* (!, -)
  final public ASTNode UnaryExpression() throws ParseException {Token t;
    ASTNode operand;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MINUS:
    case NOT:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NOT:{
        t = jj_consume_token(NOT);
recordToken(t);
        break;
        }
      case MINUS:{
        t = jj_consume_token(MINUS);
recordToken(t);
        break;
        }
      default:
        jj_la1[38] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      operand = UnaryExpression();
{if ("" != null) return new UnaryOpNode(t.image, operand, true, t.beginLine, t.beginColumn);}
      break;
      }
    case TRUE:
    case FALSE:
    case LPAREN:
    case INTEGER_LITERAL:
    case LONG_LITERAL:
    case FLOAT_LITERAL:
    case DOUBLE_LITERAL:
    case STRING_LITERAL:
    case CHAR_LITERAL:
    case IDENTIFIER:{
      operand = PrimaryExpression();
{if ("" != null) return operand;}
      break;
      }
    default:
      jj_la1[39] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

//* --------------------------------------
//* x++
  final public ASTNode PostIncrementExpression() throws ParseException {Token id, tINC;
    id = jj_consume_token(IDENTIFIER);
    tINC = jj_consume_token(INCREMENT);
recordToken(id);
            recordToken(tINC);
            symbolTable.markVariableUsed(id.image);
            {if ("" != null) return new UnaryOpNode("++", new IdentifierNode(id.image, id.beginLine, id.beginColumn),
                                  false, id.beginLine, id.beginColumn);}
    throw new Error("Missing return statement in function");
  }

//* int , long, float, double, String, char, boolean,
  final public ASTNode PrimaryExpression() throws ParseException {Token t, tLPAREN, tRPAREN;
    ASTNode node;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER_LITERAL:{
      t = jj_consume_token(INTEGER_LITERAL);
recordToken(t);
            // symbolTable.markVariableUsed(t.image); //TODO(kaizen) #change 12
            {if ("" != null) return new LiteralNode("int", t.image, t.beginLine, t.beginColumn);}
      break;
      }
    case LONG_LITERAL:{
      t = jj_consume_token(LONG_LITERAL);
recordToken(t);
            // symbolTable.markVariableUsed(t.image);//TODO(kaizen) #change 12
            {if ("" != null) return new LiteralNode("long", t.image, t.beginLine, t.beginColumn);}
      break;
      }
    case FLOAT_LITERAL:{
      t = jj_consume_token(FLOAT_LITERAL);
recordToken(t);
            // symbolTable.markVariableUsed(t.image); //TODO(kaizen) #change 12
            {if ("" != null) return new LiteralNode("float", t.image, t.beginLine, t.beginColumn);}
      break;
      }
    case DOUBLE_LITERAL:{
      t = jj_consume_token(DOUBLE_LITERAL);
recordToken(t);
            // symbolTable.markVariableUsed(t.image); //TODO(kaizen) #change 12
            {if ("" != null) return new LiteralNode("double", t.image, t.beginLine, t.beginColumn);}
      break;
      }
    case STRING_LITERAL:{
      t = jj_consume_token(STRING_LITERAL);
recordToken(t);
            // symbolTable.markVariableUsed(t.image); //TODO(kaizen) #change 12
            {if ("" != null) return new LiteralNode("String", t.image, t.beginLine, t.beginColumn);}
      break;
      }
    case CHAR_LITERAL:{
      t = jj_consume_token(CHAR_LITERAL);
recordToken(t);
            // symbolTable.markVariableUsed(t.image); //TODO(kaizen) #change 12
            {if ("" != null) return new LiteralNode("char", t.image, t.beginLine, t.beginColumn);}
      break;
      }
    case TRUE:{
      t = jj_consume_token(TRUE);
recordToken(t);
            // symbolTable.markVariableUsed(t.image);  //TODO(kaizen) #change 12
            {if ("" != null) return new LiteralNode("boolean", "true", t.beginLine, t.beginColumn);}
      break;
      }
    case FALSE:{
      t = jj_consume_token(FALSE);
recordToken(t);
            // symbolTable.markVariableUsed(t.image); //TODO(kaizen) #change 12
            {if ("" != null) return new LiteralNode("boolean", "false", t.beginLine, t.beginColumn);}
      break;
      }
    default:
      jj_la1[40] = jj_gen;
      if (jj_2_21(2147483647)) {
        node = MemberAccess();
{if ("" != null) return node;}
      } else if (jj_2_22(2147483647)) {
        node = MethodCall();
{if ("" != null) return node;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFIER:{
          t = jj_consume_token(IDENTIFIER);
recordToken(t);
            symbolTable.markVariableUsed(t.image);
            {if ("" != null) return new IdentifierNode(t.image, t.beginLine, t.beginColumn);}
          break;
          }
        case LPAREN:{
          tLPAREN = jj_consume_token(LPAREN);
recordToken(tLPAREN);
          node = Expression();
          tRPAREN = jj_consume_token(RPAREN);
recordToken(tRPAREN);
         {if ("" != null) return node;}
          break;
          }
        default:
          jj_la1[41] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public ASTNode MemberAccess() throws ParseException {Token id, tDot, tLPAREN, tRPAREN;
        MemberAccessNode memberNode;
        List<ASTNode> args = new ArrayList<ASTNode>();
        ASTNode arg;
    id = jj_consume_token(IDENTIFIER);
recordToken(id);
            memberNode = new MemberAccessNode(id.beginLine, id.beginColumn);
            memberNode.addMember(id.image);
    label_15:
    while (true) {
      tDot = jj_consume_token(DOT);
recordToken(tDot);
      id = jj_consume_token(IDENTIFIER);
recordToken(id);
                memberNode.addMember(id.image);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:{
        tLPAREN = jj_consume_token(LPAREN);
recordToken(tLPAREN);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TRUE:
        case FALSE:
        case MINUS:
        case NOT:
        case LPAREN:
        case INTEGER_LITERAL:
        case LONG_LITERAL:
        case FLOAT_LITERAL:
        case DOUBLE_LITERAL:
        case STRING_LITERAL:
        case CHAR_LITERAL:
        case IDENTIFIER:{
          arg = Expression();
args.add(arg);
          label_16:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case COMMA:{
              ;
              break;
              }
            default:
              jj_la1[42] = jj_gen;
              break label_16;
            }
            jj_consume_token(COMMA);
            arg = Expression();
args.add(arg);
          }
          break;
          }
        default:
          jj_la1[43] = jj_gen;
          ;
        }
        tRPAREN = jj_consume_token(RPAREN);
recordToken(tRPAREN);
                    MethodCallNode methodCall = new MethodCallNode(id.image, id.beginLine, id.beginColumn);
                    methodCall.setArguments(args);
                    memberNode.setMethodCall(methodCall);
        break;
        }
      default:
        jj_la1[44] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DOT:{
        ;
        break;
        }
      default:
        jj_la1[45] = jj_gen;
        break label_15;
      }
    }
{if ("" != null) return memberNode;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode MethodCall() throws ParseException {Token id, tLPAREN, tRPAREN;
        MethodCallNode methodCall;
        List<ASTNode> args = new ArrayList<ASTNode>();
        ASTNode arg;
    id = jj_consume_token(IDENTIFIER);
recordToken(id);
            symbolTable.markVariableUsed(id.image);
            methodCall = new MethodCallNode(id.image, id.beginLine, id.beginColumn);
    tLPAREN = jj_consume_token(LPAREN);
recordToken(tLPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TRUE:
    case FALSE:
    case MINUS:
    case NOT:
    case LPAREN:
    case INTEGER_LITERAL:
    case LONG_LITERAL:
    case FLOAT_LITERAL:
    case DOUBLE_LITERAL:
    case STRING_LITERAL:
    case CHAR_LITERAL:
    case IDENTIFIER:{
      arg = Expression();
args.add(arg);
      label_17:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[46] = jj_gen;
          break label_17;
        }
        jj_consume_token(COMMA);
        arg = Expression();
args.add(arg);
      }
      break;
      }
    default:
      jj_la1[47] = jj_gen;
      ;
    }
    tRPAREN = jj_consume_token(RPAREN);
recordToken(tRPAREN);
            methodCall.setArguments(args);
            {if ("" != null) return methodCall;}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_2_16(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  private boolean jj_2_17(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  private boolean jj_2_18(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  private boolean jj_2_19(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  private boolean jj_2_20(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  private boolean jj_2_21(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  private boolean jj_2_22(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  private boolean jj_3_21()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(DOT)) return true;
    return false;
  }

  private boolean jj_3_15()
 {
    if (jj_3R_19()) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_21()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  private boolean jj_3R_20()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  private boolean jj_3R_25()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(9)) {
    jj_scanpos = xsp;
    if (jj_scan_token(10)) {
    jj_scanpos = xsp;
    if (jj_scan_token(11)) {
    jj_scanpos = xsp;
    if (jj_scan_token(15)) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_23()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  private boolean jj_3R_22()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  private boolean jj_3R_18()
 {
    Token xsp;
    if (jj_3R_25()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_25()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_6()
 {
    if (jj_scan_token(VOID)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    if (jj_3R_19()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_23()) jj_scanpos = xsp;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_20()
 {
    if (jj_scan_token(DECREMENT)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_19()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(17)) {
    jj_scanpos = xsp;
    if (jj_scan_token(18)) {
    jj_scanpos = xsp;
    if (jj_scan_token(19)) {
    jj_scanpos = xsp;
    if (jj_scan_token(20)) {
    jj_scanpos = xsp;
    if (jj_scan_token(22)) {
    jj_scanpos = xsp;
    if (jj_scan_token(21)) {
    jj_scanpos = xsp;
    if (jj_scan_token(25)) {
    jj_scanpos = xsp;
    if (jj_scan_token(24)) {
    jj_scanpos = xsp;
    if (jj_scan_token(23)) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_3R_19()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_22()) jj_scanpos = xsp;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  private boolean jj_3_19()
 {
    if (jj_scan_token(INCREMENT)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_3R_18()) return true;
    if (jj_scan_token(VOID)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_18()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(DECREMENT)) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_3R_18()) return true;
    if (jj_3R_19()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_21()) jj_scanpos = xsp;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_17()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(INCREMENT)) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_18()) return true;
    if (jj_3R_19()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_20()) jj_scanpos = xsp;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  private boolean jj_3_16()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  private boolean jj_3_14()
 {
    if (jj_scan_token(DECREMENT)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_13()
 {
    if (jj_scan_token(INCREMENT)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_12()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(DECREMENT)) return true;
    return false;
  }

  private boolean jj_3_11()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(INCREMENT)) return true;
    return false;
  }

  private boolean jj_3_10()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_9()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(DOT)) return true;
    return false;
  }

  private boolean jj_3R_24()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  private boolean jj_3_8()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  private boolean jj_3_7()
 {
    if (jj_3R_19()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_24()) jj_scanpos = xsp;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_22()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public JavaParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[48];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x8e00,0x3ff8e00,0x8e00,0x0,0x8e00,0x3ff0000,0x0,0x3fe0000,0xf7fe0000,0x0,0x3fe0000,0x8e00,0x8e00,0xf4000000,0x0,0x0,0x0,0x0,0x8000000,0x3fe0000,0x0,0x0,0x0,0x0,0xf7fe0000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x40000000,0x0,0x0,0x0,0x0,0x17000073,0x40000000,0x0,0x0,0x0,0x10000070,0x7000003,0x4000003,0x40000000,0x200,0x0,0x0,0x4800803,0x3000000,0x0,0x200,0x17000073,0x80,0x100,0x0,0x400000,0x200000,0x18000,0x18000,0x1e0000,0x1e0000,0xc00,0xc00,0x3000,0x3000,0x800800,0x4800803,0x3,0x4000000,0x0,0x4800803,0x4000000,0x0,0x0,0x4800803,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x13f0,0x0,0x0,0x0,0x0,0x0,0x13f0,0x13f0,0x0,0x0,0x0,0x1000,0x13f0,0x1000,0x1000,0x0,0x13f0,0x0,0x0,0x1310,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x13f0,0x3f0,0x1000,0x2,0x13f0,0x0,0x4,0x2,0x13f0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[22];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public JavaParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public JavaParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new JavaParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 48; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 48; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public JavaParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new JavaParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 48; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 48; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public JavaParser(JavaParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 48; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(JavaParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 48; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[77];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 48; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 77; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 22; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
